/// <reference types="vite/client" />

interface ElectronAPI {
    closeApp: () => Promise<void>
    minimizeApp: () => Promise<void>
    maximizeApp: () => Promise<void>
    'window-state': () => Promise<{ isMaximized: boolean; isMinimized: boolean; isFocused: boolean } | null>
    convertFiles: (filePaths: string[], fileType: string) => Promise<unknown[]>
    onWindowStateChange: (callback: (value: boolean) => void) => void
    uploadAttachment: (id_foreign: string, type: string, info: any) => Promise<unknown>
    updateAttachment: (id: string, info: any, type: string) => Promise<unknown>
    getAllAttachment: (id_foreign: string, type: string) => Promise<unknown>
    deleteAttachment: (id_foreign: string) => Promise<unknown>
    deleteAttachmentpath: (name: string) => Promise<unknown>
    updateOnlineMonitoringData: (online_monitoring: any) => Promise<unknown>
    deleteMonitorsByAssetId: (assetId: string) => Promise<unknown>
    getOnlineMonitoringData: (assetId: string) => Promise<unknown>
    insertOnlineMonitoringData: (assetId: string, online_monitoring: any) => Promise<unknown>
    openFileDialog: (type: string) => Promise<unknown>
    uploadCustom: (name: string) => Promise<unknown>
    getNameTemplate: () => Promise<unknown>
    uploadReport: (name: string, asset: any, location: any, job: any, user_id: string) => Promise<unknown>
    getTemplateByName: (name: string) => Promise<unknown>
    deleteTempByName: (name: string) => Promise<unknown>
    updateTempByName: (data: any) => Promise<unknown>
    getColumnByName: (name: string) => Promise<unknown>
    saveTemplate: (data: any) => Promise<unknown>
    checkNameTemplateExist: (name: string) => Promise<unknown>
    getVariableFromJson: () => Promise<unknown>
    exportVariableToJon: (data: unknown) => Promise<unknown>
    exportReport: (file: any, location: any, assetType: any, asset: any, job: any, test: any, user_id: string, bushing: any, tap_changer: any) => Promise<unknown>
    login: (user: unknown) => Promise<unknown>
    signup: (user: unknown) => Promise<unknown>
    changePass: (user: unknown) => Promise<unknown>
    getAllUser: () => Promise<unknown>
    editUserInfo: (user: unknown) => Promise<unknown>
    addUser: (user: unknown) => Promise<unknown>
    deleteUser: (id: string) => Promise<unknown>
    getAllNotifications: () => Promise<unknown>
    getNotificationById: (mrid: string) => Promise<unknown>
    insertNotification: (data: unknown) => Promise<unknown>
    updateNotification: (mrid: string, data: unknown) => Promise<unknown>
    markNotificationAsRead: (mrid: string) => Promise<unknown>
    hmrideNotification: (mrid: string) => Promise<unknown>
    deleteNotification: (mrid: string) => Promise<unknown>
    deleteAllNotifications: () => Promise<unknown>
    checkForUpdate: () => Promise<unknown>
    downloadUpdate: () => Promise<unknown>
    installUpdate: () => Promise<unknown>
    onUpdateAvailable: (callback: (data: unknown) => void) => void
    onUpdateNotAvailable: (callback: (data: unknown) => void) => void
    onUpdateError: (callback: (data: unknown) => void) => void
    onDownloadProgress: (callback: (data: unknown) => void) => void
    onUpdateDownloaded: (callback: (data: unknown) => void) => void
    onAutoUpdaterLog: (callback: (data: unknown) => void) => void
    getAttachmentpath: () => Promise<unknown>
    insertAttachment: (attachment: unknown) => Promise<unknown>
    getAttachmentById: (id_foreign: string, type: string) => Promise<unknown>
    updateAttachmentById: (id: string) => Promise<unknown>
    getAttachmentByForeignIdAndType: (id_foreign: string, type: string) => Promise<unknown>
    deleteAttachmentById: (id: string) => Promise<unknown>
    openFile: (path: string) => Promise<unknown>
    downloadFile: (path: string) => Promise<unknown>
    readFileData: (filePath: string) => Promise<unknown>
    downloadFileData: (base64: string, dirFile: string) => Promise<unknown>
    insertSubstationEntity: (data: unknown) => Promise<unknown>
    getSubstationEntityByMrid: (mrid: string, user_id: string, organisation_id: string) => Promise<unknown>
    deleteSubstationEntityByMrid: (data: unknown) => Promise<unknown>
    insertTransformerEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getTransformerEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteTransformerEntity: (data: unknown) => Promise<unknown>
    insertSurgeArresterEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getSurgeArresterEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteSurgeArresterEntity: (data: unknown) => Promise<unknown>
    insertPowerCableEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getPowerCableEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deletePowerCableEntity: (data: unknown) => Promise<unknown>
    insertVoltageTransformerEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getVoltageTransformerEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteVoltageTransformerEntity: (data: unknown) => Promise<unknown>
    insertBreakerEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getBreakerEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteBreakerEntity: (data: unknown) => Promise<unknown>
    insertBushingEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getBushingEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteBushingEntity: (data: unknown) => Promise<unknown>
    insertDisconnectorEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getDisconnectorEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteDisconnectorEntity: (data: unknown) => Promise<unknown>
    insertRotatingMachineEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getRotatingMachineEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteRotatingMachineEntity: (data: unknown) => Promise<unknown>
    insertCapacitorEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getCapacitorEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteCapacitorEntity: (data: unknown) => Promise<unknown>
    insertCurrentTransformerEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getCurrentTransformerEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteCurrentTransformerEntity: (data: unknown) => Promise<unknown>
    insertReactorEntity: (old_data: unknown, data: unknown) => Promise<unknown>
    getReactorEntityByMrid: (mrid: string, psrId: string) => Promise<unknown>
    deleteReactorEntity: (data: unknown) => Promise<unknown>
    insertAssetPsr: (data: unknown) => Promise<unknown>
    getAssetPsrByMrid: (mrid: string) => Promise<unknown>
    getAssetPsrByAssetId: (assetId: string) => Promise<unknown>
    deleteAssetPsr: (data: unknown) => Promise<unknown>
    exportSubstation: (substationId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportVoltageLevel: (voltageLevelId: string, user_id: string) => Promise<unknown>
    exportBay: (bayId: string, user_id: string) => Promise<unknown>
    exportTransformer: (transformerId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportCircuitBreaker: (breakerId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportSurgeArrester: (surgeId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportPowerCable: (cableId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportVoltageTransformer: (transformerId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportCurrentTransformer: (transformerId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportBushing: (bushingId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportDisconnector: (disconnectorId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportRotatingMachine: (machineId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportCapacitor: (capacitorId: string, user_id: string, organisation_id: string) => Promise<unknown>
    exportReactor: (reactorId: string, user_id: string, organisation_id: string) => Promise<unknown>
    importSubstation: (filePath: string) => Promise<unknown>
    importVoltageLevel: (filePath: string) => Promise<unknown>
    importBay: (filePath: string) => Promise<unknown>
    importTransformer: (filePath: string) => Promise<unknown>
    importCircuitBreaker: (filePath: string) => Promise<unknown>
    importSurgeArrester: (filePath: string) => Promise<unknown>
    importPowerCable: (filePath: string) => Promise<unknown>
    importVoltageTransformer: (filePath: string) => Promise<unknown>
    importCurrentTransformer: (filePath: string) => Promise<unknown>
    importBushing: (filePath: string) => Promise<unknown>
    importDisconnector: (filePath: string) => Promise<unknown>
    importRotatingMachine: (filePath: string) => Promise<unknown>
    importCapacitor: (filePath: string) => Promise<unknown>
    importReactor: (filePath: string) => Promise<unknown>
    getSurgeArresterJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertSurgeArresterJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteSurgeArresterJob: (data: unknown) => Promise<unknown>
    getPowerCableJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertPowerCableJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deletePowerCableJob: (data: unknown) => Promise<unknown>
    getTransformerJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertTransformerJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteTransformerJob: (data: unknown) => Promise<unknown>
    getVoltageTransformerJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertVoltageTransformerJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteVoltageTransformerJob: (data: unknown) => Promise<unknown>
    getCurrentTransformerJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertCurrentTransformerJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteCurrentTransformerJob: (data: unknown) => Promise<unknown>
    getBushingJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertBushingJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteBushingJob: (data: unknown) => Promise<unknown>
    getDisconnectorJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertDisconnectorJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteDisconnectorJob: (data: unknown) => Promise<unknown>
    getRotatingMachineJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertRotatingMachineJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteRotatingMachineJob: (data: unknown) => Promise<unknown>
    getCapacitorJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertCapacitorJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteCapacitorJob: (data: unknown) => Promise<unknown>
    getCircuitBreakerJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertCircuitBreakerJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteCircuitBreakerJob: (data: unknown) => Promise<unknown>
    getReactorJobByMrid: (mrid: string, psrId: string) => Promise<unknown>
    insertReactorJob: (old_data: unknown, data: unknown) => Promise<unknown>
    deleteReactorJob: (data: unknown) => Promise<unknown>
    getParentOrganizationByMrid: (mrid: string) => Promise<unknown>
    insertParentOrganization: (data: unknown) => Promise<unknown>
    updateParentOrganization: (mrid: string, data: unknown) => Promise<unknown>
    deleteParentOrganization: (mrid: string) => Promise<unknown>
    getSubstationByMrid: (mrid: string) => Promise<unknown>
    insertSubstation: (data: unknown) => Promise<unknown>
    updateSubstation: (mrid: string, data: unknown) => Promise<unknown>
    deleteSubstation: (mrid: string) => Promise<unknown>
    getAllSubstation: () => Promise<unknown>
    getSubstationByOrganisation: (organisationId: string) => Promise<unknown>
    getLocationByMrid: (mrid: string) => Promise<unknown>
    insertLocation: (data: unknown) => Promise<unknown>
    updateLocation: (mrid: string, data: unknown) => Promise<unknown>
    deleteLocation: (mrid: string) => Promise<unknown>
    getLocationBySubstation: (substationId: string) => Promise<unknown>
    getVoltageLevelByMrid: (mrid: string) => Promise<unknown>
    insertVoltageLevel: (data: unknown) => Promise<unknown>
    updateVoltageLevel: (mrid: string, data: unknown) => Promise<unknown>
    deleteVoltageLevel: (mrid: string) => Promise<unknown>
    getAllVoltageLevel: () => Promise<unknown>
    getVoltageLevelBySubstation: (substationId: string) => Promise<unknown>
    getBayByMrid: (mrid: string) => Promise<unknown>
    insertBay: (data: unknown) => Promise<unknown>
    updateBay: (mrid: string, data: unknown) => Promise<unknown>
    deleteBay: (mrid: string) => Promise<unknown>
    getBayByVoltageLevel: (voltageLevelId: string) => Promise<unknown>
    getAssetByMrid: (mrid: string) => Promise<unknown>
    insertAsset: (data: unknown) => Promise<unknown>
    updateAsset: (mrid: string, data: unknown) => Promise<unknown>
    deleteAsset: (mrid: string) => Promise<unknown>
    getAnalogByMrid: (mrid: string) => Promise<unknown>
    insertAnalog: (data: unknown) => Promise<unknown>
    updateAnalog: (mrid: string, data: unknown) => Promise<unknown>
    deleteAnalog: (mrid: string) => Promise<unknown>
    getStringMeasurementByMrid: (mrid: string) => Promise<unknown>
    insertStringMeasurement: (data: unknown) => Promise<unknown>
    updateStringMeasurement: (mrid: string, data: unknown) => Promise<unknown>
    deleteStringMeasurement: (mrid: string) => Promise<unknown>
    getDiscreteByMrid: (mrid: string) => Promise<unknown>
    insertDiscrete: (data: unknown) => Promise<unknown>
    updateDiscrete: (mrid: string, data: unknown) => Promise<unknown>
    deleteDiscrete: (mrid: string) => Promise<unknown>
    getPersonByMrid: (mrid: string) => Promise<unknown>
    insertPerson: (data: unknown) => Promise<unknown>
    updatePerson: (mrid: string, data: unknown) => Promise<unknown>
    deletePerson: (mrid: string) => Promise<unknown>
    getProcedureByMrid: (mrid: string) => Promise<unknown>
    insertProcedure: (data: unknown) => Promise<unknown>
    updateProcedure: (mrid: string, data: unknown) => Promise<unknown>
    deleteProcedure: (mrid: string) => Promise<unknown>
    getLicenseByMrid: (mrid: string) => Promise<unknown>
    insertLicense: (data: unknown) => Promise<unknown>
    updateLicense: (mrid: string, data: unknown) => Promise<unknown>
    deleteLicense: (mrid: string) => Promise<unknown>
    checkLicense: (name: string) => Promise<unknown>
    getAllLicenses: () => Promise<unknown>
    getVoltageLevelBySubstationId: (substationId: string) => Promise<unknown>
    getBayByVoltageBySubstationId: (voltageLevel: string, substationId: string) => Promise<unknown>
    getParentOrganizationByParentMrid: (mrid: string) => Promise<unknown>
    getSubstationsInOrganisationForUser: (mrid: string, userId: string) => Promise<unknown>
    importJSON: () => Promise<unknown>
    getAssetByPsrIdAndKind: (psrId: string, kind: string) => Promise<unknown>
    getLocationByPowerSystemResourceMrid: (psrId: string) => Promise<unknown>
    getOrganisationEntityByMrid: (mrid: string) => Promise<unknown>
    getVoltageLevelEntityByMrid: (mrid: string) => Promise<unknown>
    getBayEntityByMrid: (mrid: string) => Promise<unknown>
    getPositionPointByLocationId: (locationId: string) => Promise<unknown>
    getStreetDetailByLocationId: (locationId: string) => Promise<unknown>
    getPositionPointByMrid: (mrid: string) => Promise<unknown>
    getStreetDetailByMrid: (mrid: string) => Promise<unknown>
    getStreetAddressByMrid: (mrid: string) => Promise<unknown>
    getTownDetailByMrid: (mrid: string) => Promise<unknown>
    getElectronicAddressByMrid: (mrid: string) => Promise<unknown>
    getTelephoneNumberByMrid: (mrid: string) => Promise<unknown>
    getPersonRoleByMrid: (mrid: string) => Promise<unknown>
    getPersonRoleByPersonId: (personId: string) => Promise<unknown>
    getOldWorkByMrid: (mrid: string) => Promise<unknown>
    getOldWorkByAssetId: (assetId: string) => Promise<unknown>
    getConfigurationEventByMrid: (mrid: string) => Promise<unknown>
    getAllConfigurationEvents: () => Promise<unknown>
    insertConfigurationEvent: (data: unknown) => Promise<unknown>
    getPowerSystemResourceByMrid: (mrid: string) => Promise<unknown>
    getProductAssetModelByMrid: (mrid: string) => Promise<unknown>
    getValueAliasSetByMrid: (mrid: string) => Promise<unknown>
    getValueToAliasByMrid: (mrid: string) => Promise<unknown>
    getBushingByMrid: (mrid: string) => Promise<unknown>
    getSurgeArresterByMrid: (mrid: string) => Promise<unknown>
    getPowerCableByMrid: (mrid: string) => Promise<unknown>
    updateCircuitAssessmentLimits: (asset: unknown) => Promise<unknown>
    convertFileToJSON: (filePath: string) => Promise<unknown>
}

interface Window {
    electronAPI: ElectronAPI
}
